services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user_barber
      POSTGRES_PASSWORD: password_barber
      POSTGRES_DB: barbershop_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: